import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "@/assets/styles/globals.css";
import { Providers } from "@/components/core/providers";

const roboto = Roboto({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function Layout(props: Props) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} antialiased`}>
        <Providers>{props.children}</Providers>
      </body>
    </html>
  );
}
