import type { Metadata } from "next";
import { Vazirmatn} from "next/font/google";

import "@/assets/styles/globals.css";
import { Providers } from "@/components/core/providers";

const vazirmatn = Vazirmatn({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function Layout(props: Props) {
  return (
    <html dir="rtl" lang="fa" suppressHydrationWarning>
      <body className={`${vazirmatn.className}`}>
        <Providers>{props.children}</Providers>
      </body>
    </html>
  );
}
